apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.7.3/install.yaml
  # A workflow role with all required permissions
  - workflow-role.yaml
  # A secret generated to access UI
  - server-token.yaml
# TalosOS PodSecurity compliance
patches:
  - path: patches/argo-server.yaml
  - path: patches/workflow-controller.yaml
