resources:
  - sealed-extra-secrets.yaml

patches:
  - target:
      kind: Deployment
      name: zenml
      namespace: zenml
    path: zenml-env-patch.yaml

  - target:
      kind: Deployment
      name: zenml
      namespace: zenml
    path: zenml-label-patch.yaml
