apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnativepg
resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.27.1/releases/cnpg-1.28.0.yaml
  - storageclass.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
